project:
  type: website
  output-dir: docs

website:
  title: "Derecho Comercial · UNM"
  navbar:
    left:
      - href: index.qmd
        text: Inicio

format:
  html:
    theme: cosmo
    toc: false