<!DOCTYPE html>
<html lang="es"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Prof.&nbsp;Maximiliano Romei · Derecho Comercial · Universidad Nacional de Moreno">
  <title>Derecho Comercial · UNM – Sociedades extranjeras y grupos societarios</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Sociedades extranjeras y grupos societarios</h1>
  <p class="subtitle">Extraterritorialidad · Participaciones · Control · Grupos económicos</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Prof.&nbsp;Maximiliano Romei · Derecho Comercial · Universidad Nacional de Moreno
</div>
</div>
</div>

</section>
<section id="el-problema-de-la-actuación-extraterritorial" class="slide level1">
<h1>El problema de la actuación extraterritorial</h1>
<p>Las sociedades pueden desarrollar actividades fuera del Estado en el cual fueron constituidas.</p>
<p>Esto plantea distintas preguntas:</p>
<ul>
<li>¿qué ley determina su existencia?</li>
<li>¿puede actuar en Argentina?</li>
<li>¿debe inscribirse?</li>
<li>¿es igual realizar un acto aislado que desarrollar actividad habitual?</li>
<li>¿puede participar en una sociedad argentina?</li>
<li>¿qué ocurre si fue constituida en el extranjero pero su verdadera sede o actividad principal se encuentra en Argentina?</li>
</ul>
<p>Los <strong>arts. 118 a 124 LGS</strong> organizan las respuestas.</p>
</section>
<section id="nacionalidad-de-las-sociedades" class="slide level1">
<h1>¿Nacionalidad de las sociedades?</h1>
<p>Tradicionalmente se habla de <strong>“nacionalidad de las sociedades”</strong>.</p>
<p>Pero la expresión puede inducir a confusión.</p>
<p>Las personas humanas poseen nacionalidad en sentido jurídico-político.</p>
<p>Respecto de las sociedades resulta más preciso analizar:</p>
<ul>
<li><strong>lugar de constitución</strong>;</li>
<li><strong>ley aplicable</strong>;</li>
<li><strong>domicilio o sede</strong>;</li>
<li><strong>lugar de actuación</strong>;</li>
<li><strong>localización de la actividad económica</strong>;</li>
<li><strong>control societario</strong>.</li>
</ul>
<blockquote>
<p>La pregunta jurídicamente relevante no es simplemente “¿de qué nacionalidad es?”, sino <strong>qué ordenamiento rige su existencia y bajo qué condiciones puede actuar en otro Estado</strong>.</p>
</blockquote>
</section>
<section id="nacionalidad-y-control-económico" class="slide level1">
<h1>Nacionalidad y control económico</h1>
<p>Dos cuestiones deben mantenerse separadas.</p>
<h3 id="estatuto-jurídico">Estatuto jurídico</h3>
<p>¿Dónde fue constituida la sociedad y qué ley rige su existencia y forma?</p>
<h3 id="realidad-económica">Realidad económica</h3>
<p>¿Quién controla la sociedad?<br>
¿Dónde se encuentra su actividad?<br>
¿Dónde se toman efectivamente las decisiones?</p>
<p>Una sociedad constituida en un Estado puede encontrarse económicamente controlada desde otro.</p>
<p>Por eso:</p>
<blockquote>
<p><strong>lugar de constitución y control económico no necesariamente coinciden.</strong></p>
</blockquote>
</section>
<section id="artículo-118-regla-general" class="slide level1">
<h1>Artículo 118 — Regla general</h1>
<p>El art. 118 parte de una regla fundamental:</p>
<blockquote>
<p>La sociedad constituida en el extranjero se rige, en cuanto a su <strong>existencia y forma</strong>, por las leyes del lugar de constitución.</p>
</blockquote>
<p>Estamos frente a un criterio de:</p>
<h3 id="lex-societatis">lex societatis</h3>
<p>La ley del lugar de constitución determina, en principio:</p>
<ul>
<li>si la sociedad existe;</li>
<li>cuál es su forma;</li>
<li>cuál es su estructura jurídica.</li>
</ul>
<p>Argentina reconoce esa existencia conforme al criterio establecido por la LGS.</p>
</section>
<section id="una-sociedad-extranjera-puede-actuar-en-argentina" class="slide level1">
<h1>Una sociedad extranjera puede actuar en Argentina</h1>
<p>El reconocimiento de su existencia no significa que cualquier modalidad de actuación quede sometida al mismo régimen.</p>
<p>La LGS distingue fundamentalmente:</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Actuación</th>
<th>Régimen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Actos aislados</td>
<td>Art. 118, segundo párrafo</td>
</tr>
<tr class="even">
<td>Estar en juicio</td>
<td>Art. 118, segundo párrafo</td>
</tr>
<tr class="odd">
<td>Ejercicio habitual de actos comprendidos en su objeto</td>
<td>Art. 118, tercer párrafo</td>
</tr>
<tr class="even">
<td>Establecimiento de sucursal, asiento u otra representación permanente</td>
<td>Art. 118</td>
</tr>
<tr class="odd">
<td>Participación en sociedad argentina</td>
<td>Art. 123</td>
</tr>
<tr class="even">
<td>Sede o principal objeto en Argentina</td>
<td>Art. 124</td>
</tr>
</tbody>
</table>
<p>La <strong>intensidad de la vinculación con el país</strong> determina distintas exigencias.</p>
</section>
<section id="actos-aislados" class="slide level1">
<h1>Actos aislados</h1>
<p>El artículo 118 reconoce a la sociedad constituida en el extranjero capacidad para:</p>
<blockquote>
<p><strong>realizar en el país actos aislados</strong></p>
</blockquote>
<p>y para:</p>
<blockquote>
<p><strong>estar en juicio.</strong></p>
</blockquote>
<p>Para esos supuestos no se exige el régimen de inscripción previsto para la actuación habitual.</p>
<p>Ejemplo sencillo:</p>
<p>Una sociedad extranjera celebra excepcionalmente una operación en Argentina.</p>
<p>La mera realización de ese acto no significa necesariamente que esté desarrollando aquí actividad habitual.</p>
</section>
<section id="qué-es-un-acto-aislado" class="slide level1">
<h1>¿Qué es un acto aislado?</h1>
<p>La LGS <strong>no proporciona una definición exhaustiva</strong>.</p>
<p>Por eso no alcanza con contar mecánicamente el número de operaciones.</p>
<p>Deben analizarse las circunstancias:</p>
<ul>
<li>naturaleza del acto;</li>
<li>vinculación con el objeto;</li>
<li>reiteración;</li>
<li>permanencia;</li>
<li>organización desplegada en Argentina;</li>
<li>finalidad económica de la actuación.</li>
</ul>
<blockquote>
<p>Lo relevante es distinguir una actuación circunstancial de una <strong>actividad estable o habitual en el país</strong>.</p>
</blockquote>
</section>
<section id="un-problema-práctico" class="slide level1 scrollable">
<h1>Un problema práctico</h1>
<p>Una sociedad extranjera:</p>
<ol type="1">
<li>compra un inmueble en Buenos Aires;</li>
<li>lo destina a renta;</li>
<li>posteriormente adquiere otros inmuebles;</li>
<li>celebra sucesivos contratos de locación;</li>
<li>mantiene permanentemente esa explotación.</li>
</ol>
<p>La denominación utilizada por la sociedad no resuelve el problema.</p>
<p>No alcanza con afirmar:</p>
<blockquote>
<p>“son actos aislados”.</p>
</blockquote>
<p>La realidad de la actuación puede demostrar la existencia de una <strong>actividad habitual</strong>.</p>
</section>
<section id="actuación-habitual" class="slide level1">
<h1>Actuación habitual</h1>
<p>Cuando la sociedad extranjera pretende realizar habitualmente actos comprendidos en su objeto o establecer:</p>
<ul>
<li>sucursal;</li>
<li>asiento;</li>
<li>cualquier otra especie de representación permanente,</li>
</ul>
<p>el art. 118 exige determinadas formalidades.</p>
<p>La sociedad pasa de una presencia ocasional a una:</p>
<blockquote>
<p><strong>actuación estable en el tráfico económico argentino.</strong></p>
</blockquote>
<p>Esa mayor intensidad justifica publicidad y control local.</p>
</section>
<section id="artículo-118-requisitos" class="slide level1 scrollable">
<h1>Artículo 118 — Requisitos</h1>
<p>Para la actuación habitual deberá:</p>
<ol type="1">
<li><strong>acreditar la existencia de la sociedad</strong> conforme a la ley de su país;</li>
<li><strong>fijar un domicilio en la República</strong>;</li>
<li>cumplir con la <strong>publicación e inscripción</strong> exigidas por la LGS para las sociedades que correspondan;</li>
<li>justificar la decisión de crear la representación;</li>
<li>designar a la persona a cuyo cargo estará.</li>
</ol>
<p>Si se trata de una sucursal:</p>
<blockquote>
<p>debe determinarse además el <strong>capital asignado</strong>, cuando corresponda por leyes especiales.</p>
</blockquote>
</section>
<section id="sucursal-y-filial-no-son-lo-mismo" class="slide level1">
<h1>Sucursal y filial no son lo mismo</h1>
<p>Esta distinción es fundamental.</p>
<h3 id="sucursal">Sucursal</h3>
<p>Es un establecimiento secundario de la <strong>misma sociedad extranjera</strong>.</p>
<p>No constituye una persona jurídica diferente.</p>
<h3 id="filial">Filial</h3>
<p>Es otra sociedad jurídicamente diferenciada, aunque se encuentre controlada por la sociedad extranjera.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Sucursal</th>
<th>Filial</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Misma persona jurídica</td>
<td>Persona jurídica diferente</td>
</tr>
<tr class="even">
<td>Patrimonio de la sociedad extranjera</td>
<td>Patrimonio propio</td>
</tr>
<tr class="odd">
<td>Representación local</td>
<td>Órganos propios</td>
</tr>
<tr class="even">
<td>Art. 118</td>
<td>Sociedad local + régimen de participación/control</td>
</tr>
</tbody>
</table>
</section>
<section id="artículo-119-tipo-desconocido" class="slide level1">
<h1>Artículo 119 — Tipo desconocido</h1>
<p>Puede ocurrir que la sociedad extranjera corresponda a un tipo jurídico:</p>
<blockquote>
<p><strong>desconocido por las leyes argentinas.</strong></p>
</blockquote>
<p>Esto no implica automáticamente desconocer su existencia.</p>
<p>El artículo 119 dispone que corresponde al juez de la inscripción determinar:</p>
<ul>
<li>las formalidades que deberá cumplir;</li>
<li>aplicando el criterio de <strong>máximo rigor previsto en la LGS</strong>.</li>
</ul>
<p>La diversidad de legislaciones societarias extranjeras no impide necesariamente la actuación local.</p>
</section>
<section id="artículo-120-contabilidad-separada" class="slide level1">
<h1>Artículo 120 — Contabilidad separada</h1>
<p>La sociedad comprendida en el art. 118 que desarrolla la actuación prevista legalmente debe llevar en Argentina:</p>
<blockquote>
<p><strong>contabilidad separada</strong></p>
</blockquote>
<p>y someterse al contralor correspondiente.</p>
<p>¿Por qué?</p>
<p>Porque una sociedad puede desarrollar actividades en numerosos países.</p>
<p>La contabilidad separada permite individualizar:</p>
<ul>
<li>operaciones locales;</li>
<li>activos;</li>
<li>pasivos;</li>
<li>resultados;</li>
<li>relaciones económicas correspondientes a su actuación argentina.</li>
</ul>
</section>
<section id="artículo-121-representante" class="slide level1">
<h1>Artículo 121 — Representante</h1>
<p>El representante de la sociedad constituida en el extranjero:</p>
<blockquote>
<p><strong>contrae las mismas responsabilidades que para los administradores prevé la LGS.</strong></p>
</blockquote>
<p>Y, en determinados supuestos, las correspondientes a los directores de sociedades anónimas.</p>
<p>La sociedad extranjera no puede utilizar la representación local para generar un espacio de actuación sin responsabilidad.</p>
<blockquote>
<p><strong>Actuar localmente implica también someter la gestión local a reglas de responsabilidad.</strong></p>
</blockquote>
</section>
<section id="artículo-122-emplazamiento-en-juicio" class="slide level1">
<h1>Artículo 122 — Emplazamiento en juicio</h1>
<p>La actuación internacional plantea un problema procesal muy concreto:</p>
<blockquote>
<p><strong>¿dónde se emplaza a la sociedad extranjera?</strong></p>
</blockquote>
<p>El art. 122 contempla el emplazamiento en la República.</p>
<p>Cuando existe un acto aislado:</p>
<ul>
<li>puede emplazarse en la persona del apoderado que intervino.</li>
</ul>
<p>Cuando existe sucursal, asiento o representación:</p>
<ul>
<li>puede emplazarse en la persona del representante.</li>
</ul>
<p>La actuación en Argentina genera así un punto local jurídicamente relevante para el proceso.</p>
</section>
<section id="artículo-123-participar-en-una-sociedad-argentina" class="slide level1">
<h1>Artículo 123 — Participar en una sociedad argentina</h1>
<p>Existe otra forma de actuación.</p>
<p>Una sociedad extranjera puede querer:</p>
<blockquote>
<p><strong>constituir una sociedad en Argentina o participar en una ya existente.</strong></p>
</blockquote>
<p>El art. 123 establece un régimen específico de inscripción.</p>
<p>Debe acreditar:</p>
<ul>
<li>que fue constituida conforme a las leyes de su país;</li>
<li>e inscribir su contrato social, reformas y demás documentación habilitante;</li>
</ul>
<p>en el Registro Público correspondiente.</p>
</section>
<section id="artículo-118-y-artículo-123" class="slide level1">
<h1>Artículo 118 y artículo 123</h1>
<p>No regulan exactamente el mismo supuesto.</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Art. 118</th>
<th>Art. 123</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Actuación de la propia sociedad extranjera en Argentina</td>
<td>Participación de la sociedad extranjera en una sociedad local</td>
</tr>
<tr class="even">
<td>Actos aislados o actividad habitual</td>
<td>Constitución o participación societaria</td>
</tr>
<tr class="odd">
<td>Puede existir sucursal o representación</td>
<td>La inversión se canaliza mediante otra sociedad</td>
</tr>
</tbody>
</table>
<p>Ejemplo:</p>
<p><strong>Empresa francesa abre sucursal en Buenos Aires → art. 118</strong></p>
<p><strong>Empresa francesa adquiere participación en una SA argentina → art. 123</strong></p>
<p>El material que ya veníamos trabajando identifica expresamente esta inscripción específica del art. 123. :contentReference<span data-index="2">oaicite:2</span></p>
</section>
<section id="artículo-124-la-excepción-decisiva" class="slide level1">
<h1>Artículo 124 — La excepción decisiva</h1>
<p>La LGS contempla una situación diferente:</p>
<blockquote>
<p>sociedad formalmente constituida en el extranjero, pero cuya <strong>sede se encuentra en Argentina</strong> o cuyo <strong>principal objeto está destinado a cumplirse en el país</strong>.</p>
</blockquote>
<p>En ese supuesto será considerada:</p>
<blockquote>
<p><strong>sociedad local</strong></p>
</blockquote>
<p>a los efectos del cumplimiento de las formalidades de constitución, reforma y contralor de funcionamiento.</p>
</section>
<section id="qué-busca-evitar-el-artículo-124" class="slide level1">
<h1>¿Qué busca evitar el artículo 124?</h1>
<p>El art. 124 procura impedir que la constitución extranjera sea utilizada para eludir el régimen societario argentino cuando la vinculación sustancial se encuentra aquí.</p>
<p>Puede existir:</p>
<h3 id="apariencia-formal">apariencia formal</h3>
<p>“Sociedad constituida en el extranjero”</p>
<p>pero:</p>
<h3 id="realidad-societaria">realidad societaria</h3>
<ul>
<li>sede en Argentina;</li>
<li>principal objeto destinado a cumplirse en Argentina.</li>
</ul>
<p>La norma privilegia la <strong>realidad de la localización societaria</strong> sobre la mera constitución formal extranjera.</p>
</section>
<section id="el-sistema-de-los-arts.-118-a-124" class="slide level1">
<h1>El sistema de los arts. 118 a 124</h1>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Situación</th>
<th>Norma</th>
<th>Consecuencia básica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Existencia y forma</td>
<td>118</td>
<td>Ley del lugar de constitución</td>
</tr>
<tr class="even">
<td>Acto aislado</td>
<td>118</td>
<td>Actuación admitida</td>
</tr>
<tr class="odd">
<td>Actuación habitual</td>
<td>118</td>
<td>Inscripción y representación local</td>
</tr>
<tr class="even">
<td>Tipo desconocido</td>
<td>119</td>
<td>Adecuación bajo criterio de máximo rigor</td>
</tr>
<tr class="odd">
<td>Contabilidad</td>
<td>120</td>
<td>Contabilidad separada</td>
</tr>
<tr class="even">
<td>Representante</td>
<td>121</td>
<td>Responsabilidad</td>
</tr>
<tr class="odd">
<td>Emplazamiento</td>
<td>122</td>
<td>Posibilidad de emplazar localmente</td>
</tr>
<tr class="even">
<td>Participación en sociedad argentina</td>
<td>123</td>
<td>Inscripción específica</td>
</tr>
<tr class="odd">
<td>Sede/principal objeto en Argentina</td>
<td>124</td>
<td>Tratamiento como sociedad local</td>
</tr>
</tbody>
</table>
<p>Este esquema coincide con la síntesis que ya teníamos preparada sobre sociedades extranjeras. :contentReference<span data-index="3">oaicite:3</span></p>
</section>
<section id="del-fenómeno-internacional-a-la-concentración" class="slide level1">
<h1>Del fenómeno internacional a la concentración</h1>
<p>Hasta ahora analizamos:</p>
<blockquote>
<p><strong>una sociedad actuando fuera del Estado donde fue constituida.</strong></p>
</blockquote>
<p>Pero las empresas también pueden expandirse mediante relaciones entre distintas sociedades.</p>
<p>Aparecen entonces:</p>
<ul>
<li>participaciones societarias;</li>
<li>sociedades vinculadas;</li>
<li>sociedades controlantes y controladas;</li>
<li>holdings;</li>
<li>grupos económicos.</li>
</ul>
<p>Ya no interesa solamente <strong>dónde actúa la sociedad</strong>, sino:</p>
<blockquote>
<p><strong>qué relación económica y jurídica existe entre varias sociedades.</strong></p>
</blockquote>
</section>
<section id="concentración-e-integración-empresaria" class="slide level1">
<h1>Concentración e integración empresaria</h1>
<p>La concentración económica puede producirse sin eliminar necesariamente la personalidad jurídica de las sociedades involucradas.</p>
<p>Varias sociedades pueden:</p>
<ul>
<li>conservar su personalidad;</li>
<li>conservar formalmente sus órganos;</li>
<li>conservar sus patrimonios;</li>
</ul>
<p>pero encontrarse sometidas a una:</p>
<blockquote>
<p><strong>dirección económica común o influencia dominante.</strong></p>
</blockquote>
<p>Por eso debemos distinguir:</p>
<h3 id="unidad-económica">unidad económica</h3>
<p>de</p>
<h3 id="pluralidad-jurídica.">pluralidad jurídica.</h3>
</section>
<section id="participaciones-entre-sociedades" class="slide level1">
<h1>Participaciones entre sociedades</h1>
<p>Una sociedad puede participar en el capital de otra.</p>
<p>La participación puede perseguir distintos objetivos:</p>
<ul>
<li>inversión;</li>
<li>cooperación;</li>
<li>integración productiva;</li>
<li>acceso a mercados;</li>
<li>influencia societaria;</li>
<li>control.</li>
</ul>
<p>Pero la LGS establece límites.</p>
<p>Los arts. <strong>30 a 33</strong> regulan aspectos fundamentales de las participaciones y del control entre sociedades.</p>
</section>
<section id="artículo-30-participación-según-el-tipo" class="slide level1">
<h1>Artículo 30 — Participación según el tipo</h1>
<p>El art. 30 establece restricciones vinculadas con el <strong>tipo societario</strong> de quien participa.</p>
<p>La norma determina qué sociedades pueden formar parte de sociedades de determinados tipos y contempla especialmente la participación de sociedades por acciones y en comandita por acciones.</p>
<p>La cuestión responde a una preocupación básica:</p>
<blockquote>
<p>la participación de una sociedad en otra puede modificar indirectamente el riesgo y la estructura patrimonial asumidos por sus propios socios.</p>
</blockquote>
<p>Por eso la LGS no considera indiferente <strong>en qué tipo de sociedad se participa</strong>.</p>
</section>
<section id="artículo-31-límites-a-las-participaciones" class="slide level1">
<h1>Artículo 31 — Límites a las participaciones</h1>
<p>La LGS también limita cuantitativamente determinadas participaciones de una sociedad en otra.</p>
<p>Como regla, ninguna sociedad —salvo aquellas cuyo objeto sea exclusivamente financiero o de inversión— puede adquirir o mantener participaciones por un monto superior al permitido por el art. 31 en relación con:</p>
<blockquote>
<p><strong>sus reservas libres y una parte de su capital y reservas legales.</strong></p>
</blockquote>
<p>La finalidad es impedir una excesiva inmovilización del patrimonio social en participaciones ajenas a su actividad.</p>
</section>
<section id="por-qué-limitar-las-participaciones" class="slide level1">
<h1>¿Por qué limitar las participaciones?</h1>
<p>Imaginemos una sociedad industrial.</p>
<p>Sus socios aportaron capital para desarrollar determinada actividad productiva.</p>
<p>Si la administración destina prácticamente todo el patrimonio a adquirir participaciones en otras sociedades:</p>
<ul>
<li>cambia materialmente la estructura de inversión;</li>
<li>aumenta la exposición indirecta a otros negocios;</li>
<li>puede desnaturalizar la función económica prevista;</li>
<li>puede afectar a socios y acreedores.</li>
</ul>
<p>El art. 31 establece un límite a esa política de participación.</p>
</section>
<section id="artículo-32-participaciones-recíprocas" class="slide level1">
<h1>Artículo 32 — Participaciones recíprocas</h1>
<p>Existe un problema todavía más delicado.</p>
<h3 id="sociedad-a-participa-en-sociedad-b">Sociedad A participa en Sociedad B</h3>
<p>y simultáneamente:</p>
<h3 id="sociedad-b-participa-en-sociedad-a.">Sociedad B participa en Sociedad A.</h3>
<p>La LGS prohíbe la constitución de sociedades o aumentos de capital mediante:</p>
<blockquote>
<p><strong>participaciones recíprocas.</strong></p>
</blockquote>
<p>¿Por qué?</p>
<p>Porque puede generarse una apariencia de capital que no representa recursos económicos efectivamente incorporados al conjunto.</p>
</section>
<section id="el-problema-del-capital-ficticio" class="slide level1">
<h1>El problema del capital ficticio</h1>
<p>Ejemplo simplificado:</p>
<p><strong>A aporta a B</strong></p>
<p>y</p>
<p><strong>B aporta a A</strong></p>
<p>Formalmente ambas muestran un incremento de capital.</p>
<p>Pero económicamente puede no haber ingresado nuevo patrimonio real al conjunto.</p>
<p>Por eso las participaciones recíprocas pueden producir:</p>
<ul>
<li>capitalización meramente aparente;</li>
<li>distorsión patrimonial;</li>
<li>afectación de la garantía de los acreedores;</li>
<li>estructuras circulares de control.</li>
</ul>
<p>El art. 32 procura impedir estos efectos.</p>
</section>
<section id="artículo-33-sociedades-controladas" class="slide level1">
<h1>Artículo 33 — Sociedades controladas</h1>
<p>Una sociedad es <strong>controlada</strong> cuando otra ejerce sobre ella una influencia dominante en los términos establecidos por el art. 33.</p>
<p>El control puede surgir, fundamentalmente, de:</p>
<h3 id="participación">participación</h3>
<p>posesión de votos suficientes para formar la voluntad social;</p>
<p>o de:</p>
<h3 id="influencia-dominante">influencia dominante</h3>
<p>ejercida como consecuencia de acciones, cuotas o partes de interés poseídas o por especiales vínculos existentes entre las sociedades.</p>
</section>
<section id="control-interno-y-control-externo" class="slide level1">
<h1>Control interno y control externo</h1>
<p>Didácticamente podemos distinguir:</p>
<h3 id="control-interno">Control interno</h3>
<p>Surge de la participación en el capital y de los votos.</p>
<p><strong>A posee una participación que le permite formar la voluntad de B.</strong></p>
<h3 id="control-externo">Control externo</h3>
<p>La influencia dominante deriva de <strong>especiales vínculos</strong>.</p>
<p>No depende necesariamente de poseer la mayoría del capital.</p>
<p>Por ejemplo, determinadas relaciones económicas pueden generar una dependencia capaz de otorgar influencia dominante.</p>
</section>
<section id="sociedades-vinculadas" class="slide level1">
<h1>Sociedades vinculadas</h1>
<p>El propio art. 33 diferencia control de <strong>vinculación</strong>.</p>
<p>Se consideran vinculadas, a los efectos legales, las sociedades cuando una participa en:</p>
<blockquote>
<p><strong>más del 10 % del capital de otra.</strong></p>
</blockquote>
<p>Cuando la participación supera el <strong>25 %</strong>, debe comunicarse para que la próxima asamblea ordinaria tome conocimiento.</p>
<p>Por lo tanto:</p>
<blockquote>
<p><strong>vinculación no equivale necesariamente a control.</strong></p>
</blockquote>
<p>Puede existir participación relevante sin influencia dominante.</p>
</section>
<section id="vinculación-control-y-grupo" class="slide level1">
<h1>Vinculación, control y grupo</h1>
<p>No son conceptos idénticos.</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Concepto</th>
<th>Idea central</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Participación</td>
<td>Una sociedad posee parte del capital de otra</td>
</tr>
<tr class="even">
<td>Vinculación</td>
<td>Participación relevante en los términos legales</td>
</tr>
<tr class="odd">
<td>Control</td>
<td>Capacidad de ejercer influencia dominante</td>
</tr>
<tr class="even">
<td>Grupo económico</td>
<td>Pluralidad jurídica con integración económica o dirección común</td>
</tr>
<tr class="odd">
<td>Holding</td>
<td>Sociedad cuya función central consiste en poseer participaciones en otras</td>
</tr>
</tbody>
</table>
<p>La intensidad de la integración aumenta progresivamente, aunque las categorías no forman necesariamente una secuencia obligatoria.</p>
</section>
<section id="qué-es-un-holding" class="slide level1">
<h1>¿Qué es un holding?</h1>
<p>El <strong>holding</strong> es una técnica de organización empresarial.</p>
<p>Una sociedad concentra participaciones en otras sociedades.</p>
<p>Puede utilizarse para:</p>
<ul>
<li>controlar distintas empresas;</li>
<li>coordinar decisiones;</li>
<li>organizar unidades de negocio;</li>
<li>separar riesgos;</li>
<li>estructurar inversiones.</li>
</ul>
<p>Ejemplo:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Holding H</th>
<th style="text-align: right;">Participación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sociedad Industrial A</td>
<td style="text-align: right;">90 %</td>
</tr>
<tr class="even">
<td>Sociedad Logística B</td>
<td style="text-align: right;">80 %</td>
</tr>
<tr class="odd">
<td>Sociedad Comercial C</td>
<td style="text-align: right;">100 %</td>
</tr>
</tbody>
</table>
<p>Cada sociedad conserva personalidad jurídica propia.</p>
</section>
<section id="grupo-económico" class="slide level1">
<h1>Grupo económico</h1>
<p>El grupo económico presenta una tensión característica:</p>
<blockquote>
<p><strong>unidad económica + pluralidad jurídica</strong></p>
</blockquote>
<p>Puede existir:</p>
<ul>
<li>una política empresarial común;</li>
<li>coordinación financiera;</li>
<li>dirección estratégica centralizada;</li>
<li>utilización conjunta de recursos;</li>
</ul>
<p>mientras jurídicamente subsisten:</p>
<ul>
<li>distintas sociedades;</li>
<li>distintos patrimonios;</li>
<li>distintos órganos;</li>
<li>distintas relaciones con terceros.</li>
</ul>
<p>La pertenencia a un grupo <strong>no elimina por sí sola la personalidad jurídica de cada integrante</strong>.</p>
</section>
<section id="control-no-significa-automáticamente-responsabilidad" class="slide level1">
<h1>Control no significa automáticamente responsabilidad</h1>
<p>Éste es un punto importante para evitar confusiones.</p>
<p>Que una sociedad:</p>
<ul>
<li>controle a otra;</li>
<li>pertenezca al mismo grupo;</li>
<li>o integre un holding,</li>
</ul>
<p>no significa por sí mismo que todas las sociedades pasen a responder automáticamente por todas las obligaciones del conjunto.</p>
<p>El punto de partida sigue siendo:</p>
<blockquote>
<p><strong>cada sociedad es un sujeto de derecho diferenciado.</strong></p>
</blockquote>
<p>Otra cuestión será determinar las consecuencias de conductas abusivas o de los supuestos específicos previstos por el ordenamiento.</p>
</section>
<section id="dos-fenómenos-diferentes" class="slide level1">
<h1>Dos fenómenos diferentes</h1>
<p>Podemos cerrar vinculando ambos bloques.</p>
<h3 id="extraterritorialidad">Extraterritorialidad</h3>
<p>Pregunta:</p>
<blockquote>
<p>¿Cómo actúa en Argentina una sociedad constituida en otro país?</p>
</blockquote>
<p>Normas centrales:</p>
<p><strong>arts. 118–124 LGS</strong></p>
<h3 id="integración-societaria">Integración societaria</h3>
<p>Pregunta:</p>
<blockquote>
<p>¿Cómo se relacionan patrimonialmente distintas sociedades?</p>
</blockquote>
<p>Normas centrales:</p>
<p><strong>arts. 30–33 LGS</strong></p>
<p>Ambos fenómenos responden a una misma realidad:</p>
<blockquote>
<p><strong>la empresa económica puede superar los límites de una única sociedad y de un único territorio.</strong></p>
</blockquote>
</section>
<section id="caso-integrador" class="slide level1 scrollable">
<h1>Caso integrador</h1>
<p><strong>Global Holding S.p.A.</strong> fue constituida en Italia.</p>
<p>La sociedad:</p>
<ul>
<li>adquiere el 70 % de una SA argentina;</li>
<li>controla sus decisiones sociales;</li>
<li>abre además una sucursal propia en Buenos Aires;</li>
<li>la sucursal desarrolla actividad comercial permanente;</li>
<li>la sociedad argentina controla, a su vez, una empresa logística local.</li>
</ul>
<h3 id="preguntas">Preguntas</h3>
<ol type="1">
<li>¿Qué ley rige la existencia y forma de Global Holding?</li>
<li>¿Qué régimen corresponde a su sucursal?</li>
<li>¿Qué artículo regula su participación en la SA argentina?</li>
<li>¿Existe vinculación o control?</li>
<li>¿La sociedad argentina pierde su personalidad por integrar el grupo?</li>
<li>¿Sucursal y sociedad controlada significan lo mismo?</li>
</ol>
</section>
<section id="ideas-fuerza" class="slide level1">
<h1>Ideas fuerza</h1>
<h3 id="sociedades-extranjeras">Sociedades extranjeras</h3>
<p><strong>Lugar de constitución → actuación → intensidad de la vinculación con Argentina</strong></p>
<p>No es lo mismo:</p>
<ul>
<li>acto aislado;</li>
<li>actividad habitual;</li>
<li>sucursal;</li>
<li>participación en sociedad local;</li>
<li>sociedad formalmente extranjera con sede o principal objeto local.</li>
</ul>
<h3 id="grupos-societarios">Grupos societarios</h3>
<p><strong>Participación → vinculación → control → integración empresaria</strong></p>
<p>La existencia de una unidad económica no elimina automáticamente:</p>
<blockquote>
<p><strong>la pluralidad de sujetos jurídicos.</strong></p>
</blockquote>
</section>
<section id="mapa-normativo-final" class="slide level1">
<h1>Mapa normativo final</h1>
<table class="caption-top">
<thead>
<tr class="header">
<th>Tema</th>
<th style="text-align: right;">Artículo LGS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sociedad constituida en el extranjero</td>
<td style="text-align: right;"><strong>118</strong></td>
</tr>
<tr class="even">
<td>Tipo desconocido</td>
<td style="text-align: right;"><strong>119</strong></td>
</tr>
<tr class="odd">
<td>Contabilidad</td>
<td style="text-align: right;"><strong>120</strong></td>
</tr>
<tr class="even">
<td>Representantes</td>
<td style="text-align: right;"><strong>121</strong></td>
</tr>
<tr class="odd">
<td>Emplazamiento</td>
<td style="text-align: right;"><strong>122</strong></td>
</tr>
<tr class="even">
<td>Participación en sociedad local</td>
<td style="text-align: right;"><strong>123</strong></td>
</tr>
<tr class="odd">
<td>Sociedad con sede/principal objeto local</td>
<td style="text-align: right;"><strong>124</strong></td>
</tr>
<tr class="even">
<td>Participaciones societarias</td>
<td style="text-align: right;"><strong>30–31</strong></td>
</tr>
<tr class="odd">
<td>Participaciones recíprocas</td>
<td style="text-align: right;"><strong>32</strong></td>
</tr>
<tr class="even">
<td>Control y vinculación</td>
<td style="text-align: right;"><strong>33</strong></td>
</tr>
</tbody>
</table>
<p>La lectura conjunta permite comprender dos dimensiones del derecho societario moderno:</p>
<blockquote>
<p><strong>la actuación transnacional y la integración económica entre sociedades.</strong></p>
</blockquote>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 5.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>